### ISSUE TITLE
Hardware updates for next revision

### ISSUE THREAD

**Issue by pmakin-png** [sparkfunX/Qwiic_Iridium_9603N#1]
Fix footprint of samtec connector (origin, cream layer). Does this connector need to be glued down?
Solderable/surface mount nuts.

**Comment by PaulZC** [comment]
The Samtec origin and cream are fixed in my Master branch: https://github.com/PaulZC/Qwiic_Iridium_9603N/pull/4
The SMD standoffs have been added too.
Nathan has been on the glue!
