### ISSUE TITLE
3.3 V rail voltage drops during charging

### ISSUE THREAD

**Issue by adamgarbo** [sparkfunX/Qwiic_Iridium_9603N#1]
Hi @PaulZC 

I recently concluded a successful 11-day test of the Qwiic Iridium 9603N + MicroMod Data Logging Carrier Board + Artemis Processor. Temperatures in Canada were chilly again, dropping to -25°C, and it was a good opportunity to stress test the components in the cold.

I realized I had never measured the voltage of the 3.3 V rail when the Qwiic Iridium was powering up. I was surprised to see that when charging (@ 150 mA), the Qwiic Iridium hammers the 3.3 V bus, causing it to drop to 2.9 V. I observed the same behaviour when connected to both an MMDLCB (powered by a 3.7 V LiPo) and a Qwiic Micro (3.3 V rail powered by a SparkFun Buck-Boost).

Is this expected behaviour for the Qwiic Iridium 9603N? If so, do you anticipate this voltage drop would cause any issues for other devices on the I2C bus? 

Cheers,
Adam

**Comment by PaulZC** [comment]
Hi Adam (@adamgarbo ),
Thanks for letting me know. I will dig into this as soon as time permits.
Best wishes,
Paul

**Comment by adamgarbo** [comment]
Thanks, @PaulZC!

I should note that I'm encountering this issue with V1 of the Qwiic Iridium 9603N. Did the power circuity change in V2?

Cheers,
Adam

**Comment by adamgarbo** [comment]
A quick test with a SparkFun Qwiic Micro + Qwiic Iridium 9603N. The 3.3 V bus was powered by a SparkFun Buck-Boost connected to a 12 V battery. 

Putting it on scope reveals there is definitely something strange going on. The voltage was measured on the 3.3 V/GND pins of the Qwiic iridium. 

The same behaviour was observed with a Pololu 3.3V 600 mA step-down regulator. The Buck-Boost can output up to 2 A, so the current draw of the Qwiic Iridium shouldn't be an issue for either of the regulators.

![Screen Shot 2021-02-19 at 5 44 12 PM](https://user-images.githubusercontent.com/22924092/108570100-1cb59a80-72db-11eb-878d-2885a48b32db.png)

**Comment by PaulZC** [comment]
Hi @adamgarbo ,
Thanks for this.
I wouldn't describe the trace as 'strange'. That's exactly what I would expect to see. A long period of capacitor charging, followed by short bursts of capacitor charging while the Iridium modem is on but not transmitting, followed by a longer burst to top the capacitors back up during and after the transmission.
What is unexpected is the size of the voltage drop. I would have expected it to be much smaller than that.
How are you connecting everything? Qwiic cable? Hard-soldered wires/connectors? Or breadboard + jumper wires?
I will dig into this when I get time - promise.
Best wishes,
Paul

**Comment by adamgarbo** [comment]
Hi @PaulZC,

I agree! The output of the oscilloscope is expected, but not the magnitude of the voltage drops. I just finished performing a dozen tests of different combinations of components and will update this comment once I finish reviewing the data. The two biggest culprits right now are the [SparkFun breadboards](https://www.sparkfun.com/products/12615) I recently purchased and the Qwiic Power Switch. When everything is connected directly through Qwiic cables, the voltage drop issues seem to disappear, unless the Qwiic Iridium 9603N is behind the Qwiic Power Switch.

Cheers,
Adam

**Comment by adamgarbo** [comment]
Hi @PaulZC,

Well, I think I've had enough of measuring voltages! Based on the graphs shown below, I believe we can draw a few main conclusions:

1) The Qwiic Iridium 9603N should never be placed behind the Qwiic Power Switch. This results in the most significant voltage drops (Tests 1, 2, 5, 6).
2) The SparkFun Buck-Boost does not appear to be suitable for replacing the Qwiic Micro's AP2112 regulator. It does not handle the load of the Qwiic Iridium 9603N (or RockBLOCK) very well. The 5V USB battery and AP2112 LDO results in a much stabler voltage (see Test 8)
3) The SparkFun breadboards are also causing increased voltage drops when compared to using the Qwiic connectors, even with minimal length 22 AWG jumper wires. Tests 4 vs 8 is a good example of this. Perhaps a poor quality product?

Based on these test results, I don't believe there's actually an issue with Qwiic Iridium 9603N. The problem is really with everything else! 

I'm a little worried that because I don't see a ring carrier signal that the current draw of the Qwiic Iridium 9603N may not be reflective of a real world scenario, so I may try measuring the voltage outside in the snow.

I'll leave this issue open until I perform the same tests on the MicroMod Data Logging Carrier Board. I suspect I'll encounter much the same results. 

Cheers,
Adam

## Test Configuration

All tests used the following SparkFun Qwiic components:
* Qwiic Micro SAMD21
* RV8803 RTC
* BME280 
* Qwiic Power Switch
* SAM-M8Q 
* Qwiic Iridium 9603N

**Circuit design/wiring:** 
1. SparkFun breadboard and 22 AWG jumper wires cut to a minimum length, or
2. Qwiic connectors

**Power sources:**
1. SparkFun Buck-Boost @3.3V powered from 12 V battery connected directly to 3.3V rail
2. 10 Ah 5V USB battery connected direcly to Qwiic Micro's USB port (uses AP2112 LDO)

**Measurements:**
* Capacitors manually discharged between each test
* PicoScope 4227 oscilloscope
* Channel A (blue): 3.3 V rail or directly on Qwiic 3.3V/GND pins
* Channel B (red): 3.3V/GND pins of Qwiic Iridium 9603N
* Oscilloscope output saved to CSV and plotted in Python

**Test 1:** 
* Buck-Boost @3.3V
* SparkFun breadboard + jumper wires
* Qwiic Iridium 9603N behind Qwiic Power Switch (QPS)
![test_18](https://user-images.githubusercontent.com/22924092/108632868-117b7f80-743f-11eb-9285-0f8bff50cc17.png)

**Test 2:** 
* 5V USB battery
* SparkFun breadboard + jumper wires
* Qwiic Iridium 9603N behind QPS
![test_19](https://user-images.githubusercontent.com/22924092/108632875-1dffd800-743f-11eb-98e7-9df3a14a31be.png)

**Test 3:** 
* Buck-Boost @3.3V
* SparkFun breadboard + jumper wires
* Qwiic Iridium 9603N in front QPS
![test_22](https://user-images.githubusercontent.com/22924092/108632878-21935f00-743f-11eb-8127-bc35b3ed9aba.png)

**Test 4:** 
* 5V USB battery
* SparkFun breadboard + jumper wires
* Qwiic Iridium 9603N in front QPS
![test_23](https://user-images.githubusercontent.com/22924092/108632886-2b1cc700-743f-11eb-8eeb-99359251dcbe.png)

**Test 5:**
* Buck-Boost @3.3V
* Qwiic connectors
* Qwiic Iridium 9603N behind QPS
![test_25](https://user-images.githubusercontent.com/22924092/108632922-59020b80-743f-11eb-87dc-b465930fb8b3.png)

**Test 6:** 
* 5V USB battery
* Qwiic connectors
* Qwiic Iridium 9603N behind QPS
![test_20](https://user-images.githubusercontent.com/22924092/108632891-2eb04e00-743f-11eb-9c30-f3c3149172d7.png)

**Test 7:**
* Buck-Boost @3.3V
* Qwiic connectors
* Qwiic Iridium 9603N in front of QPS
![test_24](https://user-images.githubusercontent.com/22924092/108633013-ee9d9b00-743f-11eb-9886-ec5af0425195.png)

**Test 8:** 
* 5V USB battery
* Qwiic connectors
* Qwiic Iridium 9603N in front of QPS
![test_21](https://user-images.githubusercontent.com/22924092/108632993-c746ce00-743f-11eb-9f9d-99731eb5ed80.png)

**Comment by PaulZC** [comment]
Hi Adam (@adamgarbo ),
Nice very methodical work! ;-) Thank you.
The Qwiic Power Switch drop is a surprise. The breadboard + jumpers less so. (Think about the **tiny** contact area between the breadboard 'fingers' or 'jaws' and your solid-core jumper wires.)
The QPS uses a DMG2305 P-FET and looking at the datasheet the R<sub>DS(ON)</sub> varies with both temperature and V<sub>GS</sub>. But I would expect it to be around 50mOhms at 3.3V and room temperature. If the Qwiic Iridium is drawing around 300mA (roughly double the charging current), the voltage drop across the FET should be around 15mV, not ~ten times that... Maybe we're not driving the gate hard enough? I wonder what would happen if R5 were changed to 100R or 10R?
I will investigate when I get time, but like you say, the Qwiic Iridium itself appears to be behaving as expected.
Thanks!
Paul

**Comment by adamgarbo** [comment]
Thanks, Paul!

I'm happy to create a separate issue on the QPS repository but it's not a high priority.

Regarding wiring, wouldn't the "jaws" of the breadboard technically have more surface area contact with the AWG 22 jumper wire than the Qwiic JST connector/28 AWG wire? SparkFun doesn't have any information on the max current rating of their breadboards, but I would expect that they should be able to handle ~0.3 A without any difficulty. Given this, I suspect that the breadboard is also the cause of the problems I was having when trying to power a RockBLOCK at ~450 mA. 

Cheers,
Adam
